name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23' 
        distribution: 'temurin'
   
    # naviguer dans dossier contenant le pom.xml
    - name: Navigate to project folder
      run: cd "IFT2255-Groupe-18/Devoir 3/workspace"

    - name: Build and test with Maven
      run: mvn clean install
